# Generated by Django 3.0.5 on 2020-12-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201205_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
